steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'OSRM_BACKEND_URL=$_ROUTING_URL', '-t', 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
  id: build-backend

- name: 'gcr.io/cloud-builders/docker'
  id: push-backend
  args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/backend:$COMMIT_SHA']
  waitFor:
  - build-backend

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  id: deploy-backend
  waitFor:
  - push-backend
  args:
  - 'run'
  - 'deploy'
  - 'backend'
  - '--min-instances=0'
  - '--max-instances=1'
  - '--memory=512MiB'
  - '--cpu=1'
  - '--image'
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/backend:$COMMIT_SHA'
  - '--region'
  - 'europe-north1'

images:
- 'europe-north1-docker.pkg.dev/$PROJECT_ID/images/backend:$COMMIT_SHA'
