apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: radlnavi-routing
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/radlnavi/images/test@sha256:f1028e914c9bff089fc7e476a730b2de5884fe2c7b9bb56859035bee512e70e5
        ports:
        - containerPort: 8000
        env:
        - name: OSRM_BACKEND_URL
          value: localhost:8080
        resources:
          limits:
            memory: 3Gi
            cpu: "1"
      - image: europe-north1-docker.pkg.dev/radlnavi/images/backend:f59037e145b55ef5de568e5d0d25d988bce25c0d
        resources:
          limits:
            memory: 2Gi
            cpu: "1"